### ISSUE TITLE
Uncaught TypeError: Cannot read properties of null (reading 'createElement')

### ISSUE THREAD

**Issue by ziyoulihen** [ProseMirror/prosemirror-menu#37]
My test code: 

```typescript
import { EditorState } from "prosemirror-state";
import { EditorView } from "prosemirror-view";
import { Schema, DOMParser, Mark } from "prosemirror-model";
import { schema } from "prosemirror-schema-basic";
import { addListNodes } from "prosemirror-schema-list";
import { exampleSetup } from "prosemirror-example-setup";

class MarkEditor {
  #schema: Schema;
  #root: HTMLElement;
  #view: EditorView;

  constructor() {
    this.#schema = new Schema({
      nodes: addListNodes(schema.spec.nodes, "paragraph block*", "block"),
      marks: schema.spec.marks,
    });

    this.#root = document.createElement("div");

    this.#view = new EditorView(this.#root, {
      state: EditorState.create({
        doc: DOMParser.fromSchema(this.#schema).parse(document.querySelector("#content")!),
        plugins: exampleSetup({ schema: this.#schema })
      }),
    });
  }

  mount(container: HTMLElement) {
    container.appendChild(this.#root);
  }
}

const editor = new MarkEditor();

editor.mount(document.querySelector("#app")!);

```

Getting this error:

```
index.js:17  Uncaught TypeError: Cannot read properties of null (reading 'createElement')
    at getIcon (index.js:17:20)
    at MenuItem.render (index.js:80:27)
    at renderGrouped (index.js:285:44)
    at new MenuBarView (index.js:493:31)
    at Object.view (index.js:475:35)
    at EditorView.updatePluginViews (index.js:5255:55)
    at new EditorView (index.js:5087:14)
    at new MarkEditor (main.ts:21:18)
    at main.ts:34:16
```

And my package.json is:

```json
{
  "name": "markeditor",
  "private": true,
  "version": "0.0.0",
  "type": "module",
  "scripts": {
    "dev": "vite",
    "build": "tsc && vite build",
    "preview": "vite preview"
  },
  "devDependencies": {
    "typescript": "^5.0.2",
    "vite": "^4.4.5"
  },
  "dependencies": {
    "prosemirror-example-setup": "^1.2.2",
    "prosemirror-model": "^1.19.3",
    "prosemirror-schema-basic": "^1.2.2",
    "prosemirror-schema-list": "^1.3.0",
    "prosemirror-state": "^1.4.3",
    "prosemirror-view": "^1.31.7"
  }
}

```

**Comment by ziyoulihen** [comment]
![image](https://github.com/ProseMirror/prosemirror-menu/assets/67856832/8b7f064a-3269-4e6a-a1e3-6fe027b1aab9)

It seems that `root`  is a `Document` instance and the `ownerDocuement` attribute of root is null.

**Comment by marijnh** [comment]
Attached patch should avoid this.
